server:
  port: 8761

eureka:
  instance:
    hostname: discovery.vothanhtuyen.id.vn
    homePageUrl: https://${eureka.instance.hostname}/
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
  client:
    registerWithEureka: false
    fetchRegistry: false
